# frozen_string_literal: true

desc 'Render .woodpecker/build.yaml from the image matrix'
task :woodpecker do
  raise 'metadata.yaml not found' unless File.exist?('metadata.yaml')
  raise 'lib/ not found — run rake install first' unless File.exist?('lib')

  all_images = build_objects_array(
    metadata: YAML.safe_load(File.read('metadata.yaml')),
    default_metadata: YAML.safe_load(File.read('lib/metadata-defaults.yaml'))
  )

  ci_image  = 'bcit.io/library/woodpecker-crucible:latest'
  when_push = [{ 'event' => %w[push manual], 'branch' => 'main' }]
  auth_setup = [
    'mkdir -p /root/.docker',
    'printf \'%s\' "$HARBOR_CONFIG" > /root/.docker/config.json'
  ]
  base_env = {
    'HARBOR_CONFIG'      => { 'from_secret' => 'harbor_config' },
    'REGISTRY_AUTH_FILE' => '/root/.docker/config.json'
  }

  steps = []

  # render step: stamps a new build ID, re-renders Containerfiles and pipeline
  steps << {
    'name'        => 'render',
    'image'       => ci_image,
    'pull'        => true,
    'privileged'  => true,
    'when'        => [{ 'event' => %w[push manual], 'branch' => 'main' }],
    'environment' => {
      'HARBOR_CONFIG'      => { 'from_secret' => 'harbor_config' },
      'REGISTRY_AUTH_FILE' => '/root/.docker/config.json'
    },
    'commands'    => auth_setup + ['rake install', 'rake template', 'rake woodpecker']
  }

  # one build step per version x variant
  all_images.each do |image|
    variant_label = image.variant.empty? ? 'base' : image.variant
    step_name     = ['build', image.version, variant_label].reject(&:empty?).join('-')

    step_depends = ['render']
    if image.depends_on
      dep_label = image.depends_on.empty? ? 'base' : image.depends_on
      dep_name  = ['build', image.version, dep_label].reject(&:empty?).join('-')
      step_depends << dep_name
    end

    env = {
      'HARBOR_CONFIG'      => { 'from_secret' => 'harbor_config' },
      'REGISTRY_AUTH_FILE' => '/root/.docker/config.json',
      'KEEP_BUILD'         => '1'
    }
    env['VERSION'] = image.version unless image.version.empty?
    env['VARIANT'] = image.variant unless image.variant.empty?

    steps << {
      'name'        => step_name,
      'image'       => ci_image,
      'pull'        => true,
      'privileged'  => true,
      'depends_on'  => step_depends,
      'when'        => [{ 'event' => %w[push manual], 'branch' => 'main' }],
      'environment' => env,
      'commands'    => auth_setup + [
        'rake install',
        'rake template',
        'rake build',
        'rake test',
        'rake scan',
        'rake tag',
        'rake push'
      ]
    }
  end

  FileUtils.mkdir_p('.woodpecker')
  File.open('.woodpecker/build.yaml', 'w') do |f|
    f.puts '# Generated by rake woodpecker — do not edit by hand'
    f.puts({ 'steps' => steps }.to_yaml.sub(/\A---\n/, ''))
  end

  puts 'Rendered .woodpecker/build.yaml'.green
end
